### ISSUE TITLE
SSAS hang situation - Request, New idea

### ISSUE THREAD

**Issue by YinnWong** [jonburchel/SSASDiag#1]
Hi Jon,

It will be great to have a feature to take dump on ssas process during hang situation. 

Thank you!
Yinn

**Comment by jonburchel** [comment]
Thank you Yinn!  This was a fantastic idea to add hang dumps to data collection.  It is checked in now at https://github.com/jonburchel/SSASDiag/commit/acaab868a1ef98401202429dfb7ebc8aa9d6be8e and will be in the next release, coming very soon.
