### ISSUE TITLE
Win32 Error 1368

### ISSUE THREAD

**Issue by ejmereen** [jonburchel/SSASDiag#10]
From the SSASDiag log (bold part is the issue):

Initializing SSAS diagnostics collection at 07/23/2019 14:39:02 UTC-05:00.
Installing collection service SSASDiag_MSSQLServer.. ...
Starting service...
Collection service SSASDiag_MSSQLServer is running.
Collection initializing... ... 
**Failure impersonating client connection.  Win32 error code was: 1368**
Scheduled diagnostic collection starts automatically at 07/23/2019 14:40:00 UTC-05:00.
Collection scheduled to stop automatically at 07/23/2019 16:38:00 UTC-05:00.
Time remaining until collection starts: 00:00:00:25
Stopping collection at 07/23/2019 14:39:34 UTC-05:00.
Stoppped SSAS diagnostics collection at 07/23/2019 14:39:34 UTC-05:00.
SSASDiag completed at 07/23/2019 14:39:34 UTC-05:00.

**Comment by jonburchel** [comment]
Fixed in commit https://github.com/ssasdiag/SSASDiag/commit/03e0a6b648adeed35af7fc8f458264cbf939e37a
