### ISSUE TITLE
unable to determine version in the GUI

### ISSUE THREAD

**Issue by ghost** [jonburchel/SSASDiag#2]
can you add the build into the title bar for the tool like windbg does? or add it to the about section

**Comment by jonburchel** [comment]
Yes I will do this in the next minor release and close this issue when I publish it in the next week or so.  Thanks for the great idea!

**Comment by jonburchel** [comment]
Btw your family is beautiful in your profile pic...  lol

**Comment by jonburchel** [comment]
I've fixed this now in the following checkin!  Thanks again for the idea!

https://github.com/ssasdiag/SSASDiag/commit/b1f8ce4d6351826ba798e15a34077448d2525f39#diff-77ba39c75aa8cc8fd5b3aa38a3a13379
