### ISSUE TITLE
crash on startup

### ISSUE THREAD

**Issue by gertch** [jonburchel/SSASDiag#3]
Using 1.1.1.114  release. it crashes on Startup after a few seconds with unhandled .net Framework exception.

  Problem Event Name:	CLR20r3
  Problem Signature 01:	SSASDiag.exe
  Problem Signature 02:	1.1.1.115
  Problem Signature 03:	5915e4cf
  Problem Signature 04:	System
  Problem Signature 05:	4.7.2114.0
  Problem Signature 06:	59a63a25
  Problem Signature 07:	a01
  Problem Signature 08:	87
  Problem Signature 09:	System.Net.WebException
  OS Version:	6.3.9600.2.0.0.400.8
  Locale ID:	1033
  Additional Information 1:	e2c6
  Additional Information 2:	e2c65cc203a01a37116ab6e8e4adbfee
  Additional Information 3:	84c0
  Additional Information 4:	84c0eb0f566556a03d4ae6325990de97

apparently a code 401 (Access denied).
was run as admin.

>	System.dll!System.Net.WebClient.OpenRead(System.Uri address) Line 457	C#
 	mscorlib.dll!System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx) Line 954	C#
 	mscorlib.dll!System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx) Line 902	C#
 	mscorlib.dll!System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state) Line 891	C#
 	mscorlib.dll!System.Threading.ThreadHelper.ThreadStart() Line 111	C#
 	[Native to Managed Transition]	
 	mscorlib.ni.dll!00007ff9cd9b6472()	Unknown

**Comment by jonburchel** [comment]
Thank you for submitting this Gert!  I think this issue should be fixed now.  Can you try it once more with the 1.1.1.118 release to see?  Once you confirm I'll close this issue.  If it persists can you run from command line with ssasdiag /debug, and send me the debug output log that is generated in the same directory?
