### ISSUE TITLE
Program crashing on startup

### ISSUE THREAD

**Issue by george4e** [jonburchel/SSASDiag#8]
Hi,

When trying to run SSASDiag (as Administrator) on a server (Microsoft Windows Server 2012 R2 Standard) it crashes with:

Problem signature:
  Problem Event Name:	CLR20r3
  Problem Signature 01:	SSASDiag.exe
  Problem Signature 02:	1.1.1.128
  Problem Signature 03:	5aa02192
  Problem Signature 04:	mscorlib
  Problem Signature 05:	4.0.30319.34014
  Problem Signature 06:	52e0b676
  Problem Signature 07:	451b
  Problem Signature 08:	9a
  Problem Signature 09:	System.IO.InvalidDataException
  OS Version:	6.3.9600.2.0.0.272.7
  Locale ID:	7177
  Additional Information 1:	64bf
  Additional Information 2:	64bf000e39e931ef1c4eb37735d2ec31
  Additional Information 3:	de8e
  Additional Information 4:	de8efd79f9565c5fd35f8a139182a380

I then downloaded the source and tried to compile it but get errors:

Severity	Code	Description	Project	File	Line
Error	CS0433	The type 'MajorObject' exists in both 'Microsoft.AnalysisServices.Core, Version=14.0.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91' and 'Microsoft.AnalysisServices, Version=12.0.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91'	SSASDiag	C:\WORK\Download\SQLServer\SSASDiag-1.1.1.128\SSASDiag-1.1.1.128\SSASDiag\SSASDiag\CDiagnosticsCollector.cs	958

Please assist.

**Comment by jonburchel** [comment]
This is fixed in the 1.1.1.144 release.
