### ISSUE TITLE
Issue with Visual studio 2017

### ISSUE THREAD

**Issue by tanmoycuat** [jonburchel/SSASDiag#9]
It does't work with visual studio 2017.Is there any help regarding this?

**Comment by jonburchel** [comment]
Did you do a full build?  Or get an error opening the project?  What failure did you get?  I wasn't aware it wasn't 2017 compatible anymore, but the project may not be backward compatible with 2017 since I've been working in 2019 now for several check ins, so it could require 2019 now too.
